spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://192.168.1.113:5432/spring-yana-temp?createDatabaseIfNotExist=true&useSSL=false}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: 192.168.1.113:29092

open:
  api:
    title: API document
    version: 1.0.0
    description: API document
    license: API License
    server:
      url: http://192.168.1.202:${server.port}
      description: ${API_DESCRIPTION:DUMMY-API-TITLE}
server:
  port: 8080

jwt:
  token:
    #    secretKey: IguQSCqT093SQEaF6wsziGck8GP0/43Ot2gW3Zi1CCMd79fl5Nj96GeSotDwSafr
    secretKey: kpSZeCvebW2082lEUsgScg+x7NevIEmhXhJ1ZSqeUJ8=
    refreshKey: n2s2rLnrvw6n/JKN5fCqLKAYD42TNXOkO2RuvKup9oU=
    #    expirationMs: 864000000 # 10 days
    expirationMs: 300000 # 5 minutes
    refreshExpirationMs: 8640000000 # 100 days


logging:
  level:
    org.springframework.security: DEBUG
    com.ra: DEBUG