spring:
  config:
    activate:
      on-profile: dev

open:
  api:
    title: API document
    version: 1.0.0
    description: API document
    license: API License
    server:
      url: http://192.168.1.202:${server.port}
      description: ${API_DESCRIPTION:DUMMY-API-TITLE}
server:
  port: 8080
