server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080
# database
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://192.168.1.113:3306/spring-again?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  cloudinary:
    cloud-name: dbeb5elqt
    api-key: 261249265348835
    api-secret: XDlMaEdnkzcBV3PeiPn02QxNZrk



---
spring:
  config:
    activate:
      on-profile: dev

open:
  api:
    title: API document
    version: 1.0.0
    description: API document
    license: API License
    server:
      url: http://192.168.1.202:8080
      description: Development server

---
spring:
  config:
    activate:
      on-profile: test

open:
  api:
    title: API document
    version: 1.0.0
    description: API document
    license: API License
    server:
      url: http://192.168.1.202:8081
      description: Test server

---
spring:
  config:
    activate:
      on-profile: prod

open:
  api:
    title: API document
    version: 1.0.0
    description: API document
    license: API License
    server:
      url: http://192.168.1.202:8082
      description: Product server